### ISSUE TITLE
Public Endpoint checks for storage.googleapis.com and production.cloudflare.docker.com always fail

### ISSUE THREAD

**Issue by scottdarrah** [swimlane/swimlane-environment-validator#11]
Talked to Ryan about these, he said he hasn't found an endpoint that reliably returns a success code. we shouldn't 'ship' with these failing - maybe add a comment at the end of the script that you will manually need to verify access to those? not sure...

+--------------------------------------------------------------------------------+
|                                Public Endpoints                                |
+---------------------------------------------------------+-------------+--------+
|                         Endpoint                        | Status Code | Result |
+---------------------------------------------------------+-------------+--------+
|           https://get.swimlane.io/nginx-health          |    Passed   |  200   |
|                   https://k8s.kurl.sh                   |    Passed   |  200   |
|                     https://kurl.sh                     |    Passed   |  200   |
| https://kurl-sh.s3.amazonaws.com/dist/ekco-0.6.0.tar.gz |    Passed   |  200   |
|            https://registry.replicated.com/v2           |    Passed   |  301   |
|           https://proxy.replicated.com/healthz          |    Passed   |  200   |
|                    https://k8s.gcr.io                   |    Passed   |  302   |
|              https://storage.googleapis.com             |    Failed   |  400   |
|                     https://quay.io                     |    Passed   |  200   |
|                  https://replicated.app                 |    Passed   |  200   |
|               https://auth.docker.io/token              |    Passed   |  200   |
|               https://registry-1.docker.io              |    Passed   |  200   |
|         https://production.cloudflare.docker.com        |    Failed   |  403   |
|              https://files.pythonhosted.org             |    Passed   |  200   |
|                     https://pypi.org                    |    Passed   |  200   |
+---------------------------------------------------------+-------------+--------+

add something here?
|---------------------------------------------------------------------------------------------------------------------------------------------|
|                                                      !!! Additional Manual Checks !!!                                                       |
|                                   Each SPI Node must have a unique hostname as determined by hostnamectl.                                   |
|                                             Each SPI Node should have DNS-resolvable hostnames.                                             |
|                             Each SPI Node must have reliable and consistent time. An NTP daemon is recommended.                             |
|_____________________________________________________________________________________________________________________________________________|

**Comment by bagel-dawg** [comment]
a potential fix to this is verify that the two URLs are actually needed. I believe storage.googleapis.com is, but im not so sure about production.cloudflare.docker.com is

**Comment by bagel-dawg** [comment]
the way the test is written, if I accept 400 or 403 for these, I'll have to accept 400 or 403 for all of the endpoints

so if a proxy were to return a 403 because somethings misconfigured (which is entirely possible), the validator would give false results

**Comment by mjneth** [comment]
Could the function that checks them accept a url and a list of passing status codes? Would that be awful?

**Comment by bagel-dawg** [comment]
:thinking: 

probably wouldn't be terrible, ill look at implementing that.
