### ISSUE TITLE
Ubuntu Server timesync check 

### ISSUE THREAD

**Issue by mlyborg** [swimlane/swimlane-environment-validator#19]
systemctl status systemd-timesyncd.service
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

timedatectl
               Local time: Sat 2021-02-20 19:25:10 UTC
           Universal time: Sat 2021-02-20 19:25:10 UTC
                 RTC time: Sat 2021-02-20 19:25:10
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

**Comment by bagel-dawg** [comment]
@mlyborg Are you saying that you want systemd-timesyncd.service checked in addition to ntpd and chronyd? Easy enough to do, just want to make sure that's what you wanted to see.

**Comment by mlyborg** [comment]
That would be excellent!

./Thanks
