### ISSUE TITLE
Allow ~(-2-3%) for Minimum Required storage

### ISSUE THREAD

**Issue by mlyborg** [swimlane/swimlane-environment-validator#20]
Since most administrators will provision exactly what's in the installation guide, please allow for 2-3%
<img width="1401" alt="Provisioned_Storage" src="https://user-images.githubusercontent.com/32066342/108606633-512b6400-7378-11eb-87ff-44afb4b99f08.png">

**Comment by bagel-dawg** [comment]
@mlyborg this effectively makes the minimum storage requirements to be the following

/var/lib/docker - 95GB
/opt - 47.5GB
/ - 47.5GB
/var/openebs - 291GB

Do you see that as an acceptable margin? We can keep "friendly" values that you see in the minimum requirements output presently.

**Comment by mlyborg** [comment]
I just wanted to ensure that all are aware that if someone follows the partitioning guidance as per `https://swimlane.com/knowledge-center/install/Swimlane_Platform_Installer/System_Requirements/#general-prerequisites`, the environment validator will return `Failed` (since after the partitions have been formatted, the `Total Space Size` will most likely be less than actual)

**Comment by bagel-dawg** [comment]
roger, will merge the PR to help with that.
