### ISSUE TITLE
Add /var/lib/kubelet partition check

### ISSUE THREAD

**Issue by jbrodersen** [swimlane/swimlane-environment-validator#28]
System requirements now include the following which are not presently validated with the script.

/var/lib/kubelet | 100 GB | Kubernetes runtime, ephemeral storage, and in flight snapshot temporary storage | Snapshot size and pod temporary storage increasing

**Comment by mjneth** [comment]
Looks like this added back on May 5th as well: https://github.com/swimlane/swimlane-environment-validator/commit/c33c85181d4b2c9e935d575d620b00e836c883ca
