### ISSUE TITLE
Disk size calculation for Directory Sizes chart needs to ease up! df -h shows 100GB but output shows 99.950199...

### ISSUE THREAD

**Issue by scottdarrah** [swimlane/swimlane-environment-validator#6]
ran the environment validator and I got a fail for /var/lib/docker:
/var/lib/docker | 99.95019912719727  | 0.03147930001303368 | /var/lib/docker is not large enough to meet minimum requirements. | Failed

my df -h shows 100GB on the nose: 
/dev/sdc1                100G   33M  100G   1% /var/lib/docker

This should be sufficient to pass.

**Comment by bagel-dawg** [comment]
please see https://github.com/swimlane/swimlane-environment-validator/issues/10#issuecomment-780070659
